build:
  version: "3.0"

loans:
  message: "Welcome to MaleBank loans related local APIs"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaa@malebank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
