spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to MaleBank accounts related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Production Owner"
    email: "aishiwaya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
