build:
  version: "2.0"

cards:
  message: "Welcome to MaleBank cards related QA APIs"
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@malebank.com"
  onCallSupport:
    - (310) 875-4367
    - (915) 236-1267
