build:
  version: "3.0"

cards:
  message: "Welcome to MaleBank cards related local APIs"
  contactDetails:
    name: "Thanapong Y - Developer"
    email: "malethanapong@malebank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932