#spring.application.name=configserver

spring:
  config:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
          # search-locations: "classpath:/config"
#          search-locations: "file:///Users//maleyy//Documents//config"
        git:
          uri: "https://github.com/MaleTNP/malebank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#      group:
#        readiness:
#          include:
#            - rabbit

encrypt:
  key: "btdCZHsGplWNOtwvxwLmsvoNvpB1i5aQ"

server:
  port: 8071
